### ISSUE TITLE
提高代码健壮性

### ISSUE THREAD

**Issue by kitelife** [youngsterxyf/redis-sentinel-manager#6]
在某些sentinel或redis服务器挂了之后，redis-sentinel-manager运行可能会遇到问题

**Comment by gslsf223** [comment]
/opt/redis-sentinel-ui/gulpfile.js:7
const gulp = require('gulp');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/opt/redis-sentinel-ui/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/opt/redis-sentinel-ui/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/opt/redis-sentinel-ui/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/opt/redis-sentinel-ui/node_modules/gulp/node_modules/liftoff/index.js:190:9)
